language: php
sudo: false

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer require php-coveralls/php-coveralls
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover clover.xml
  - ./vendor/bin/phpcs

after_script:
  - php vendor/bin/coveralls -v