language: php
sudo: false

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer require php-coveralls/php-coveralls:^2.2.0
  - composer self-update
  - composer install -n

script:
  - ./vendor/bin/phpunit --coverage-clover clover.xml
  - ./vendor/bin/phpcs

after_success:
  - ./vendor/bin/php-coveralls --coverage_clover=clover.xml